### PR TITLE
feat: bump the tf module version

### PR DESCRIPTION
**Pull request by rhilgenbergbastos-ch**
https://companieshouse.atlassian.net/browse/JU-889

### CODE REVIEW

**Comment by ch-code-analysis** [comment]
CI: IaC Security warnings found!

**Review by chillier-ch — APPROVED** [review]

**Comment by ch-code-analysis** [comment]
CI: IaC Security warnings found!

**Comment by ch-code-analysis** [comment]
CI: IaC Security warnings found!

**Comment by ch-code-analysis** [comment]
CI: IaC Security warnings found!

**Comment by ch-code-analysis** [comment]
CI: IaC Security warnings found!

**Comment by ch-code-analysis** [comment]
CI: No IaC security warnings found

**Pull request merged**
